### ISSUE TITLE
Polish Front End

### ISSUE THREAD

**Issue by aryan-soni** [aryan-soni/eecs3311-project-bravo#30]
Should be completed after the models are done and the controller logic has been decoupled from the views.

No need to make the views dynamically work here, the general goal is to just ensure that they reflect the information that will come from the models and that the styling is as desired. 

Moreover, as per the requirements, try adding error handling where-ever possible. Note that incorrect inputs may be tested when we demo our code

**Comment by o-saund** [comment]
Please take a look at the visualization's labels and adjust them accordingly in the models when polishing the front en.
