### ISSUE TITLE
Fix Sequence Diagram

### ISSUE THREAD

**Issue by aryan-soni** [aryan-soni/eecs3311-project-bravo#34]
There was a brief critique for Deliverable 1 related to Sequence Diagrams.

Perhaps clarify with the TA what was wrong and make a change if need be. If there's not enough time to get to this, feel free to close the issue.

**Comment by mikailkarimi** [comment]
Fixed the issue marked in blue by the reviewer. Not sure what their comment in red is in reference to as the diagram in question is explained and indicated as required by the document (does he just want us to remove the diagram). If anyone has any ideas please let me know.

**Comment by aryan-soni** [comment]
> Fixed the issue marked in blue by the reviewer. Not sure what their comment in red is in reference to as the diagram in question is explained and indicated as required by the document (does he just want us to remove the diagram). If anyone has any ideas please let me know.

Perhaps get in touch with the TA over Slack?

**Comment by mikailkarimi** [comment]
TA still hasn't responded to my question after a week. Curious if we think multiple people should message or reach out directly to the professor.

**Comment by aryan-soni** [comment]
I'd suggest sending a quick follow-up to the TA, and reaching out to the Professor as well.

**Comment by mikailkarimi** [comment]
![image](https://user-images.githubusercontent.com/89994900/227797453-5663012d-1983-48cf-af60-4558d6cb2740.png)

Should be good!
